[tool.black]
line-length = 120
target-version = ["py38"]

[tool.isort]
line_length=120
multi_line_output=3
include_trailing_comma="True"
use_parentheses="True"
force_grid_wrap=0

[tool.unimport]
exclude='(__init__.py)|venv|env'
remove="True"
